Add Signup Page
HangarTeam1/twitter-front-react pull request #4
Opened 2023-08-18 06:07 UTC by arnoldbgm

# Description

Implementation of the signup page, installation of the Roboto font and new svg images.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

![image](https://github.com/HangarTeam1/twitter-front-react/assets/108824074/398794f1-2d45-4637-bf0f-c9c2b940dbbc)

2023-08-18 15:49 UTC, linder3hs requested changes

2023-08-18 15:49 UTC, linder3hs commented on src/assets/index.ts
> +export { default as apple } from "./logo/apple.svg";
los logos de apple y google debería ir en otra carpeta como `social-media`

2023-08-18 15:49 UTC, linder3hs commented on src/pages/signup/index.tsx
> +        {/* Black logo starts */}
eliminar comentarios

2023-08-18 15:49 UTC, linder3hs commented on src/pages/signup/index.tsx
> +  const footerLinks = [
el footer debe ser parte del layout

2023-08-18 15:49 UTC, linder3hs commented on src/pages/signup/index.tsx
> +                <span className='text-[#1E97E1] cursor-pointer'> Terms of Service </span>
los colores como `#1E97E1` deben ser agregados al archivo de tailwind

2023-08-18 15:49 UTC, linder3hs commented on src/pages/signup/index.tsx
> +              <button className='w-[403px] h-[62px] bg-transparent border border-gray-300 border-opacity-80 rounded-full font-roboto text-base font-normal leading-normal flex items-center justify-cen
usar medidas fijas en px no es recomendable recuerda que tailwind es pensado en mobile first

2023-08-20 14:52 UTC, arnoldbgm commented on src/assets/index.ts
> +export { default as apple } from "./logo/apple.svg";
Solucionado 😎

2023-08-20 14:53 UTC, arnoldbgm commented on src/pages/signup/index.tsx
> +        {/* Black logo starts */}
Solucionado 😎😎

2023-08-20 14:53 UTC, arnoldbgm commented on src/pages/signup/index.tsx
> +  const footerLinks = [
No me sale, me da un scroll inncesario, ayuda ahi sensei :(

2023-08-20 14:54 UTC, arnoldbgm commented on src/pages/signup/index.tsx
> +                <span className='text-[#1E97E1] cursor-pointer'> Terms of Service </span>
Solucionado 😎

2023-08-20 14:54 UTC, arnoldbgm commented on src/pages/signup/index.tsx
> +              <button className='w-[403px] h-[62px] bg-transparent border border-gray-300 border-opacity-80 rounded-full font-roboto text-base font-normal leading-normal flex items-center justify-cen
Solucionado 😎

2023-08-21 18:19 UTC, merged