Create account view
HangarTeam1/twitter-front-react pull request #5
Opened 2023-08-23 03:58 UTC by arnoldbgm

# Description

Implementacion de la vista crear cuenta, there are problems to pass the props to the datepicker

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

2023-08-23 15:55 UTC, linder3hs requested changes

2023-08-23 15:55 UTC, linder3hs commented on src/pages/signup/components/DatePicker/index.tsx
> +  const getMonthName = (month: number) => {
seria bueno extraer esto a otra carpeta como `herlpers` o `utils`

2023-08-23 15:55 UTC, linder3hs commented on src/pages/signup/components/DatePicker/index.tsx
> +import React, { useState } from "react";
no hace falta import React solo debería ser así

```js
import { useState } from "react";
```

2023-08-23 15:55 UTC, linder3hs commented on src/pages/signup/components/DatePicker/index.tsx
> +  const daysInMonth = (month: number, year: number) => {
igual, mover a una carpeta de utilidad

2023-08-23 15:55 UTC, linder3hs commented on src/pages/signup/components/index.ts
> +export { default as Modal} from './Modal'
falta un espacio `Modal }`

2023-08-23 15:55 UTC, linder3hs commented on src/pages/signup/components/SocialButton/index.tsx
> +  setShowModal?: (value: boolean) => void;
al hacer esto estamos amarrando esto a sea un modal solo debería recibir un `onClick` así no importa si es un modal u otra acción, el componente debe ser independiente a cualquier acción de la vista principal

2023-08-23 15:55 UTC, linder3hs commented on src/pages/signup/index.tsx
> +      <Modal isInvisible={showModal} onClose={()=> setShowModal(false)}/>
para el uso de modales recomiendo usar Headless UI 
 
[info de modal](https://headlessui.com/react/dialog)

2023-08-30 16:20 UTC, arnoldbgm commented on src/pages/signup/components/SocialButton/index.tsx
> +  setShowModal?: (value: boolean) => void;
Esta parte no lo entendi bien

2023-08-30 16:23 UTC, arnoldbgm commented on src/pages/signup/components/DatePicker/index.tsx
> +  const getMonthName = (month: number) => {
Solucionado ✅

2023-08-30 16:23 UTC, arnoldbgm commented on src/pages/signup/components/DatePicker/index.tsx
> +import React, { useState } from "react";
Solucionado ✅

2023-08-30 16:23 UTC, arnoldbgm commented on src/pages/signup/components/DatePicker/index.tsx
> +  const daysInMonth = (month: number, year: number) => {
Solucionado ✅

2023-08-30 16:23 UTC, arnoldbgm commented on src/pages/signup/components/index.ts
> +export { default as Modal} from './Modal'
Solucionado ✅

2023-08-30 16:23 UTC, arnoldbgm commented on src/pages/signup/index.tsx
> +      <Modal isInvisible={showModal} onClose={()=> setShowModal(false)}/>
Solucionado ✅

2023-09-03 04:22 UTC, merged